apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: iscmldaazchcaptureorder 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iscmldaazchcaptureorder 
    spec:
      containers:
        - name: iscmldaazchcaptureorder 
          image: acrchallenge131210.azurecr.io/iscmldaazchcaptureorder
          ports:
          - containerPort: 8080